CREATE TABLE job_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    location VARCHAR(255),
    posting_url VARCHAR(255),
    notes VARCHAR(2000),
    status VARCHAR(255) NOT NULL
        CHECK (status IN ('SAVED', 'APPLIED', 'INTERVIEW', 'OFFER', 'REJECTED')),
    application_date DATE,
    interview_date DATE
);
