CREATE TABLE app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL
);

-- Existing applications stay unassigned until the local database owner assigns them.
ALTER TABLE job_applications ADD COLUMN owner_id BIGINT;
ALTER TABLE job_applications ADD CONSTRAINT fk_application_owner
    FOREIGN KEY (owner_id) REFERENCES app_users(id);
CREATE INDEX idx_applications_owner_id ON job_applications(owner_id, id);
