spring.application.name=devtrack
spring.config.import=optional:file:../.env[.properties]

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/devtrack}
spring.datasource.username=${DATABASE_USER:devtrack}
spring.datasource.password=${POSTGRES_PASSWORD}

server.address=127.0.0.1
server.port=8080

management.endpoints.web.base-path=/api
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
